name: Lint

on: [workflow_call]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Add PNPM 8
        uses: pnpm/action-setup@v4
        with:
          version: 8

      - name: Install packages
        run: pnpm install

      - name: Run lint
        run: pnpm run lint

      - name: Generate eslint report
        run: pnpm run lint:output

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: eslint-lint-report
          path: ./eslint-report.json
          retention-days: 14
